version: '3.8'

services:
  nginx:
    image: nginx:alpine
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 10s
      timeout: 5s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 4M
      replicas: 3
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first
      restart_policy:
        condition: on-failure
    volumes:
      - ./configs/nginx/nginx.conf:/etc/nginx/nginx.conf

  load_balancer:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./configs/nginx/lb.nginx.conf:/etc/nginx/nginx.conf:ro