version: '3.8'

services:
  nginx:
    image: nginx:alpine
    # command: sleep 15s && nginx
    # command: nginx -g daemon off
    container_name: nginx
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80